### ISSUE TITLE
How did you find out the protocol?

### ISSUE THREAD

**Issue by BillWSY** [yoshito-n-students/bno055_usb_stick#5]
I am trying to add calibration to the software, but I can't find any protocol spec for the USB stick. How did you find out the protocol?

**Comment by yoshito-okada** [comment]
I don't understand detailed protocol too.  I just monitored the serial port grabed by Bosch Desktop Development by using an external software like https://www.eltima.com/products/serial-port-monitor/, and imported commands to my code.  You may be able to add new commands by the same approach.

If you expand my code, feel free to make a pull request!

**Comment by BillWSY** [comment]
Thanks. That was what I imagined as well. It seems the software does not provide calibration data read back / write on the UI, so I canceled my BNO055 USB Stick order.

Do you know if the software can read back calibration data? If it can, I will certainly re-place the order and contribute!

**Comment by yoshito-okada** [comment]
I have no idea about reading/writing calibration data from/to the IMU.

But if you just want to know whether your IMU is calibrated or not, you can see `bno055_usb_stick_msgs::Output::calibration_status` published from a node.
The following datasheet says that calibration is simultaneously performed during pose estimation in the section 3.10.
So you can just wait for the calibration status to match your favorite condition instead of restoring previous calibration data.
https://cdn-shop.adafruit.com/datasheets/BST_BNO055_DS000_12.pdf

**Comment by BillWSY** [comment]
Thank you very much for the information. My concern was if I install the IMU on a robot, I might no longer have the flexibility to move it around and let it calibrate. I will still try to get a USB stick to play with it -- and I will let you know if there is some discovery.

Much appreciated!

**Comment by yoshito-okada** [comment]
I think your concern is reasonable.  However, I have installed this IMU into several ground robots whose maximum speed is less than 1m/s to just measure pose or do SLAM and never found problems about pose estimated by the IMU (even if not waiting calibrated).

**Comment by BillWSY** [comment]
That's very good to know. I wanted to test this on an autonomous car before we decide to get a super expensive IMU. I will get one and play with it -- and play a little bit with the protocol.
